name: Feature branch
on:
  push:
    branches-ignore:
      master

jobs:
  test-unit:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run test
        run: |
          npm ci
          npm run test

  docker-build:
    name: Build Docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
          docker build .

  infrastructure:
    name: Show infrastructure
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Show infrastructure
        id: showinfrastructure
        run: |
          cd infra
          npm ci
          npm run build

          # todo: a diff from `npm run cdk diff` would be more useful

          infra=$(npm run cdk synth)
          infra="${infra//'%'/'%25'}"
          infra="${infra//$'\n'/'%0A'}"
          infra="${infra//$'\r'/'%0D'}"
          echo "::set-output name=infra::$infra"
      - uses: jwalton/gh-find-current-pr@v1.0.2
        id: finder
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: marocchino/sticky-pull-request-comment@v1.4.0
        name: Add comment to PR
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          header: Infrastructure
          number: ${{ steps.finder.outputs.pr }}
          message: |
            Infrastructure for commit `${{ github.sha }}`:
            <details>
              <summary>Click to see the log</summary>
              ```yml
              ${{ steps.showinfrastructure.outputs.infra }}
              ```
            </details>
