name: Feature branch
on:
  push:
    branches-ignore:
      master

jobs:
  test-unit:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup
        run: |
          npm ci
          npm run test
