name: Master
on:
  push:
    branches:
      master

jobs:
  build-and-push-docker-image:
    name: Build and push docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build and push to ECR
        id: build-and-push-docker-image
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        run: |
          BASE_URL="$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com"

          aws ecr get-login-password | docker login --username AWS --password-stdin "$BASE_URL"

          # todo: package.json version should be used as the image tag
          docker build -t "$BASE_URL"/loan-calc:latest .

          docker push "$BASE_URL"/loan-calc:latest

  deploy-cloudformation-stack:
    name: Deploy CloudFormation stack
    needs: build-and-push-docker-image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy CloudFormation stack
        id: deploy-cloudformation-stack
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        run: |
          IMAGE_URL="$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/loan-calc:latest"

          cd infra
          npm ci
          npm run build
          npm run cdk deploy -- --require-approval never
